import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'vi' | 'en';

export const translations = {
  vi: {
    // Header nav
    nav_about: 'Về chúng tôi',
    nav_experiences: 'Trải nghiệm',
    nav_how: 'Cách hoạt động',
    nav_community: 'Cộng đồng',
    nav_faq: 'Hỏi đáp',
    nav_dashboard: 'Bảng điều khiển',
    nav_preview: 'Tour đang mở bán',
    nav_login: 'Đăng nhập',
    nav_logout: 'Đăng xuất',
    nav_dark_on: 'Chuyển giao diện tối',
    nav_dark_off: 'Chuyển giao diện sáng',
    lang_toggle: 'Đổi sang tiếng Anh',

    // Hero section
    hero_eyebrow: 'Tour địa phương tại Việt Nam',
    hero_title: 'Đặt tour rõ giá, rõ lịch trình, có đánh giá thật từ người dùng.',
    hero_desc: 'Khám phá Vịnh Hạ Long, Hội An, Bát Tràng, Sa Pa và nhiều trải nghiệm bản địa với quy trình đặt tour đơn giản, bình luận minh bạch.',
    hero_cta_tours: 'Xem tour',
    hero_cta_host: 'Đăng ký làm host',
    hero_stat_safe: 'Bảo đảm an toàn',
    hero_stat_quality: 'Chất lượng',
    hero_stat_review: 'Đánh giá chân thực',

    // About section
    about_eyebrow: 'Về chúng tôi',
    about_title: 'Một quy trình đặt tour gọn, dễ kiểm soát',
    about_desc: 'Khách xem tour và bình luận trước khi đăng nhập. Người dùng đã đăng nhập được đặt tour, hủy đơn đang chờ và gửi đánh giá.',
    about_f1_title: 'Tour rõ thông tin',
    about_f1_text: 'Mỗi tour có địa điểm, thời lượng, giá VNĐ, ảnh và danh mục để người dùng lọc nhanh.',
    about_f2_title: 'Host cộng đồng',
    about_f2_text: 'Kết nối du khách với các host và hướng dẫn viên địa phương đã được xác minh để mang lại trải nghiệm chân thực hơn.',
    about_f3_title: 'Thông tin đặt tour chính xác',
    about_f3_text: 'Email, số điện thoại, ngày khởi hành và số lượng khách được kiểm tra tự động để hạn chế sai sót khi đặt tour.',

    // Experiences section
    exp_eyebrow: 'Trải nghiệm',
    exp_title: 'Tour đang mở bán',
    exp_desc: 'Chi phí tour được niêm yết theo VNĐ và cập nhật trực tiếp trên hệ thống. Tour chưa có đánh giá sẽ hiển thị 0.0 sao.',
    exp_search_placeholder: 'Tìm theo tên tour, địa điểm hoặc danh mục',
    exp_price_from: 'Giá từ...',
    exp_price_to: 'Đến giá...',
    exp_all_categories: 'Tất cả danh mục',
    exp_show_more: 'Xem thêm',
    exp_book: 'Đặt tour',
    exp_view_detail: 'Xem chi tiết',
    exp_no_result: 'Không tìm thấy tour phù hợp.',
    exp_wishlist_login: 'Vui lòng đăng nhập để thêm vào danh sách yêu thích',
    exp_guests: 'khách',
    exp_full: 'Hết chỗ',
    exp_not_open: 'Chưa mở',

    // How it works
    how_eyebrow: 'Cách hoạt động',
    how_title: 'Ba bước để bắt đầu hành trình',
    how_desc: 'Quy trình được giữ ngắn để người dùng mới cũng thao tác nhanh.',
    how_s1_title: 'Khám phá tour',
    how_s1_text: 'Duyệt danh sách các tour địa phương, xem đánh giá thực tế và chọn trải nghiệm phù hợp.',
    how_s2_title: 'Đặt chỗ dễ dàng',
    how_s2_text: 'Chọn ngày, điền thông tin liên lạc và xác nhận đặt tour chỉ trong vài bước đơn giản.',
    how_s3_title: 'Trải nghiệm thực tế',
    how_s3_text: 'Tham gia tour và chia sẻ đánh giá chân thực để giúp cộng đồng du lịch ngày càng tốt hơn.',

    // Community
    community_eyebrow: 'Cộng đồng',
    community_title: 'Chia sẻ hành trình của bạn',
    community_view_all: 'Xem tất cả bài viết',

    // Host register
    host_eyebrow: 'Dành cho Host',
    host_title: 'Trở thành host và chia sẻ trải nghiệm địa phương',
    host_desc: 'Điền thông tin đăng ký và chúng tôi sẽ liên hệ để xác minh trong vòng 24 giờ.',
    host_name: 'Họ và tên',
    host_email: 'Email',
    host_phone: 'Số điện thoại',
    host_address: 'Địa chỉ thường trú',
    host_id: 'Số CMND/CCCD',
    host_exp_location: 'Địa điểm hoạt động',
    host_exp_desc: 'Mô tả trải nghiệm bạn muốn chia sẻ',
    host_submit: 'Gửi đăng ký',
    host_submitting: 'Đang gửi...',
    host_form_required_error: 'Vui lòng nhập đầy đủ thông tin đăng ký host',
    host_contact_invalid_error: 'Email hoặc số điện thoại không hợp lệ',
    host_id_invalid_error: 'Số CCCD/Passport phải gồm đúng 12 chữ số',
    host_desc_min_error: 'Mô tả cần tối thiểu 20 ký tự',
    host_submit_error: 'Không thể gửi đăng ký host',
    host_submit_success: 'Đã gửi đăng ký host thành công! Admin sẽ duyệt đơn của bạn.',
    host_session_expired: 'Phiên đăng nhập đã hết hạn, vui lòng đăng nhập lại.',
    host_data_error: 'Không thể đọc dữ liệu',
    host_load_error: 'Không thể tải dữ liệu quản trị',
    host_image_type_error: 'Vui lòng chọn file hình ảnh.',
    host_upload_error: 'Lỗi tải ảnh lên',
    host_tour_required_error: 'Vui lòng nhập đầy đủ thông tin tour',
    host_price_min_error: 'Giá tour phải từ 1.000 VNĐ trở lên',
    host_max_guests_error: 'Số khách tối đa phải từ 1 đến 1000',
    host_close_date_error: 'Ngày đóng tour phải sau hoặc bằng ngày mở tour',
    host_profile_success: 'Cập nhật hồ sơ thành công!',
    host_delete_title: 'Xóa tour',
    host_delete_message: 'Bạn có chắc chắn muốn xóa tour này không? Mọi dữ liệu liên quan sẽ bị mất.',
    host_review_request_title: 'Yêu cầu duyệt tour',
    host_review_request_message: 'Tour sẽ được gửi cho Admin duyệt. Bạn sẽ nhận được thông báo sau khi Admin phản hồi.',
    host_refund_confirm: 'Xác nhận bạn đã hoàn tiền cho khách hàng?',
    host_refund_success: 'Đã cập nhật trạng thái hoàn tiền thành công.',
    host_refund_error: 'Lỗi xử lý hoàn tiền',
    host_review_success: 'Đã gửi đánh giá khách hàng thành công',
    host_preview_no_booking: 'Host không cần đặt tour trong chế độ xem trước!',
    admin_preview_no_booking: 'Quản trị viên không cần đặt tour trong chế độ xem trước!',

    // Review
    review_eyebrow: 'Đánh giá',
    review_title: 'Đánh giá từ khách hàng',
    review_desc: 'Người dùng đã đăng nhập có thể gửi đánh giá bằng số sao và bình luận. Điểm đánh giá trung bình của tour được cập nhật tự động dựa trên phản hồi từ khách hàng.',
    review_submit_title: 'Gửi đánh giá của bạn',
    review_select_tour: 'Chọn tour',
    review_comment_placeholder: 'Chia sẻ trải nghiệm của bạn...',
    review_submit: 'Gửi đánh giá',
    review_submitting: 'Đang gửi...',
    review_login_required: 'Vui lòng đăng nhập để gửi đánh giá.',
    review_choose_tour_error: 'Vui lòng chọn tour cần đánh giá',
    review_comment_min_error: 'Bình luận cần tối thiểu 5 ký tự',
    review_submit_error: 'Không thể gửi bình luận',
    review_submit_success: 'Đã gửi bình luận thành công',

    // Footer
    footer_desc: 'Nền tảng đặt tour địa phương tại Việt Nam với quy trình đơn giản và minh bạch.',
    footer_links: 'Liên kết nhanh',
    footer_contact: 'Liên hệ',
    footer_rights: 'Đã đăng ký bản quyền.',

    // FAQ
    faq_eyebrow: 'Hỏi đáp',
    faq_title: 'Câu hỏi thường gặp',
    faq_q1: 'Tôi chưa đăng nhập có đặt tour được không?',
    faq_a1: 'Khách chưa đăng nhập vẫn xem được toàn bộ tour và bình luận, nhưng cần đăng nhập hoặc đăng ký tài khoản trước khi đặt tour và gửi đánh giá.',
    faq_q2: 'Số sao đánh giá được tính như thế nào?',
    faq_a2: 'Tour mới mặc định 0 sao. Khi người dùng gửi đánh giá, hệ thống tự tính điểm trung bình và tăng số lượt đánh giá.',
    faq_q3: 'Tôi có thể hủy đơn đã đặt không?',
    faq_a3: 'Người dùng có thể hủy đơn khi đơn còn ở trạng thái chờ xử lý. Sau khi được xác nhận, bạn nên liên hệ hỗ trợ để thay đổi lịch.',

    // Bookings (user profile)
    booking_my: 'Đơn đặt tour của tôi',
    booking_tour: 'Tour',
    booking_date: 'Ngày khởi hành',
    booking_guests: 'Số khách',
    booking_total: 'Tổng tiền',
    booking_status: 'Trạng thái',

    // Host Tabs
    host_tab_overview: 'Tổng quan',
    host_tab_experiences: 'Quản lý Tour',
    host_tab_bookings: 'Đơn đặt tour',
    host_tab_reviews: 'Đánh giá',
    host_tab_profile: 'Hồ sơ cá nhân',

    // Host Dashboard
    host_dashboard_eyebrow: 'Bảng điều khiển',
    host_dashboard_title: 'Quản trị VietTour',
    host_dashboard_desc: 'Quản lý tour, đơn đặt, và hồ sơ của bạn.',
    host_stat_tours: 'Tour đang bán',
    host_stat_reviews: 'Đánh giá',
    host_stat_pending: 'Đơn chờ duyệt',
    host_stat_revenue: 'Thực nhận dự kiến',
    host_chart_title: 'Biểu đồ doanh thu',
    host_chart_desc: 'Thống kê thực nhận trong 7 ngày gần nhất',
    host_chart_total: 'Tổng 7 ngày',
    host_new_bookings: 'Đơn mới',
    host_new_reviews: 'Đánh giá mới',
    host_no_bookings: 'Chưa có đơn đặt tour.',
    host_no_reviews: 'Chưa có đánh giá nào.',
    host_refresh: 'Làm mới',
    host_chart_earning: 'Thực nhận',
    host_loading: 'Đang tải dữ liệu...',
    host_preview_title: 'Tour đang mở bán',
    host_preview_desc: 'Xem trước danh sách tour hiển thị với khách hàng.',
    host_search_ph: 'Tìm theo tên tour, địa điểm hoặc danh mục',
    host_no_desc: 'Chưa có mô tả cho tour này.',
    host_max_guests_day: 'khách/ngày',
    host_booking_period: 'Nhận đặt',
    host_price_from: 'Giá từ',
    host_view_detail: 'Chi tiết',
    host_no_match: 'Không tìm thấy tour phù hợp.',
    host_load_more: 'Xem thêm',
    host_manage_tours: 'Quản lý tour',
    host_editing_tour: 'Đang sửa tour',
    host_add_tour: 'Thêm tour',
    host_form_name: 'Tên tour',
    host_form_name_ph: 'Nhập tên tour',
    host_form_location: 'Địa điểm',
    host_form_location_ph: 'Nhập địa điểm',
    host_form_duration: 'Thời lượng',
    host_form_duration_ph: 'VD: 2 ngày 1 đêm',
    host_form_price: 'Giá (VND)',
    host_form_price_ph: 'Nhập giá',
    host_form_category: 'Danh mục',
    host_form_category_ph: 'Chọn danh mục',
    host_form_max_guests: 'Tổng khách tối đa (toàn tour)',
    host_form_daily_max: 'Khách tối đa mỗi ngày',
    host_form_open_date: 'Mở đặt từ ngày',
    host_form_close_date: 'Đóng đặt sau ngày',
    host_form_rooms: 'Số phòng',
    host_form_beds: 'Số giường',
    host_form_children: 'Cho trẻ em tham gia',
    host_form_min_age: 'Tuổi tối thiểu',
    host_form_child_max_age: 'Trẻ em tối đa (tuổi)',
    host_form_child_discount: 'Giảm giá cho trẻ em (%)',
    host_form_amenities: 'Tiện ích',
    host_form_amenities_ph: 'Nhập các tiện ích (cách nhau bằng dấu phẩy)',
    host_form_image: 'Ảnh đại diện',
    host_form_image_ph: 'URL hoặc tải lên',
    host_form_upload: 'Tải lên',
    host_form_gallery: 'Danh sách ảnh phụ',
    host_form_gallery_ph: 'Các link cách nhau bằng dấu phẩy hoặc khoảng trắng',
    host_form_desc: 'Mô tả chi tiết',
    host_form_desc_ph: 'Nhập mô tả chi tiết về tour để thu hút khách hàng',
    host_form_save_review: 'Lưu & Gửi duyệt cập nhật',
    host_form_save: 'Lưu',
    host_form_cancel: 'Hủy',
    host_table_tour: 'Tour',
    host_table_category: 'Danh mục',
    host_table_price: 'Giá',
    host_table_capacity: 'Sức chứa',
    host_table_period: 'Thời gian mở',
    host_table_rating: 'Đánh giá',
    host_table_actions: 'Thao tác',
    host_guests_total: 'khách (tổng)',
    host_per_day: '/ngày',
    host_status_closed: 'Đã đóng (đủ khách)',
    host_status_pending_review: 'Chờ Admin duyệt',
    host_status_pending_update: 'Chờ duyệt cập nhật',
    host_status_hidden: 'Đã ẩn',
    host_status_draft: 'Bản nháp',
    host_status_open: 'Đang mở',
    host_status_not_open: 'Chưa mở',
    host_status_closed_simple: 'Đã đóng',
    host_reopen: 'Mở lại',
    host_submit_review: 'Gửi duyệt',
    host_waiting: 'Đang chờ...',
    host_no_tours: 'Chưa có tour trong hệ thống.',
    host_manage_bookings: 'Quản lý đơn đặt tour',
    host_table_order: 'Đơn',
    host_table_contact: 'Liên hệ',
    host_table_schedule: 'Ngày/Lịch đi',
    host_table_finance: 'Tài chính',
    host_table_status: 'Trạng thái',
    host_guests: 'khách',
    host_schedule_id: 'Lịch ID',
    host_earning: 'Thực nhận',
    host_opt_pending: 'Chờ xử lý',
    host_opt_confirmed: 'Đã xác nhận',
    host_opt_cancelled: 'Đã hủy',
    host_opt_unpaid: 'Chưa thanh toán',
    host_opt_paid: 'Đã thanh toán',
    host_refund_req: 'Yêu cầu hoàn tiền',
    host_refunded: 'Đã hoàn tiền',
    host_eval_customer: 'Đánh giá khách',
    host_reviews_title: 'Đánh giá từ khách hàng',
    host_tour_deleted: 'Tour đã xóa',
    host_profile_title: 'Hồ sơ cá nhân',
    host_profile_name: 'Tên hiển thị',
    host_profile_phone: 'Số điện thoại',
    host_profile_id: 'CMND/CCCD',
    host_profile_address: 'Địa chỉ',
    host_profile_area: 'Khu vực hoạt động',
    host_profile_desc: 'Mô tả bản thân',
    host_profile_update: 'Cập nhật hồ sơ',
    host_changed: 'Thay đổi',
    host_from: 'từ',
    host_to: 'thành',
    host_no_changes: 'Không có thay đổi dữ liệu nào đáng kể.',
    host_err_old_version: 'Không thể đọc được dữ liệu phiên bản cũ.',
    host_update_detail: 'Chi tiết cập nhật (So sánh với bản cũ)',
    host_empty: 'Trống',
    host_yes: 'Có',
    host_no: 'Không',

    // Categories
    cat_nature: 'Thiên nhiên',
    cat_culture: 'Văn hóa',
    cat_history: 'Lịch sử',
    cat_culinary: 'Ẩm thực',
    cat_adventure: 'Phiêu lưu',
    cat_resort: 'Nghỉ dưỡng',
    cat_discovery: 'Khám phá',
    cat_experience: 'Trải nghiệm',

    // Auth
    auth_login_title: 'Đăng nhập',
    auth_login_desc: 'Đăng nhập để đặt tour, bình luận và trải nghiệm các dịch vụ.',
    auth_email: 'EMAIL',
    auth_email_ph: 'name@example.com',
    auth_password: 'MẬT KHẨU',
    auth_password_forgot: 'Quên mật khẩu?',
    auth_password_ph: 'Tối thiểu 6 ký tự',
    auth_login_btn: 'Đăng nhập',
    auth_no_account: 'Chưa có tài khoản?',
    auth_register_free: 'Đăng ký miễn phí',
    auth_register_title: 'Đăng ký tài khoản',
    auth_register_desc: 'Tạo tài khoản để đặt tour và bình luận.',
    auth_fullname: 'HỌ VÀ TÊN',
    auth_fullname_ph: 'Nguyễn Văn A',
    auth_register_btn: 'Đăng ký',
    auth_has_account: 'Đã có tài khoản?',
    auth_login_now: 'Đăng nhập ngay',
    auth_forgot_title: 'Quên mật khẩu',
    auth_forgot_desc: 'Nhập email và mật khẩu mới của bạn để đổi mật khẩu.',
    auth_password_new: 'Mật khẩu mới',
    auth_password_confirm: 'Xác nhận mật khẩu mới',
    auth_password_new_ph: 'Mật khẩu mới (tối thiểu 6 ký tự)',
    auth_password_confirm_ph: 'Nhập lại mật khẩu mới',
    auth_reset_btn: 'Đổi mật khẩu',
    auth_or_continue_with: 'Hoặc tiếp tục với',
    auth_google_error: 'Đăng nhập Google thất bại',
    auth_google_cancel: 'Bạn đã huỷ đăng nhập Google',
    auth_google_email_exists: 'Email này đã được đăng ký. Đang đăng nhập...',

    // User Profile
    profile_title: 'Thông tin cá nhân',
    profile_bookings: 'Đơn đã đặt',
    profile_cancelled: 'Đơn đã hủy',
    profile_favorites: 'Yêu thích',
    profile_email_fixed: 'EMAIL (KHÔNG ĐỔI)',
    profile_fullname: 'HỌ TÊN',
    profile_phone: 'SỐ ĐIỆN THOẠI',
    profile_avatar: 'TẢI ẢNH ĐẠI DIỆN',
    profile_avatar_select: 'Chọn tệp',
    profile_avatar_none: 'Không có...được chọn',
    profile_address: 'ĐỊA CHỈ',
    profile_save: 'Lưu thay đổi',
    profile_booking_date: 'Ngày đặt:',
    profile_guests: 'khách',
    profile_payment: 'Thanh toán:',
    profile_no_cancelled: 'Bạn chưa hủy đơn tour nào.',
    profile_no_wishlists: 'Bạn chưa có tour yêu thích nào.',

    // More detail
    detail_review_count: 'bình luận',
    detail_reviews_count: 'bình luận',
    detail_tour_count: 'tour',
    detail_tours_count: 'tour',
    detail_hour: 'giờ',
    detail_rating_count: 'đánh giá',

    booking_status_pending: 'Chờ duyệt',
    booking_status_confirmed: 'Đã xác nhận',
    booking_status_cancelled: 'Đã hủy',
    booking_payment_unpaid: 'Chưa thanh toán',
    booking_payment_paid: 'Đã thanh toán',
    booking_payment_refunded: 'Đã hoàn tiền',

    // Misc
    loading: 'Đang tải...',
    error_generic: 'Có lỗi xảy ra. Vui lòng thử lại.',
    logout_success: 'Đăng xuất thành công',
    tour_not_bookable: 'Tour này chưa mở hoặc đã hết thời gian nhận đặt.',
    // Detail Modal
    detail_host_info: 'Thông tin Host',
    detail_capacity: 'Sức chứa',
    detail_booking_open: 'Nhận đặt',
    detail_child_policy: 'Chính sách trẻ em',
    detail_status: 'Trạng thái',
    detail_room: 'phòng',
    detail_rooms: 'phòng',
    detail_bed: 'giường',
    detail_beds: 'giường',
    detail_amenities: 'Tiện ích',
    detail_schedules: 'Lịch khởi hành sắp tới',
    detail_gallery: 'Thư viện ảnh',
    detail_description: 'Mô tả trải nghiệm',
    detail_map: 'Bản đồ khu vực',
    detail_close: 'Đóng',
    detail_book_now: 'Đặt tour ngay',
    detail_tour_closed: 'Tour đã đóng',
    detail_age_from: 'Tuổi tham gia: từ',
    detail_age_to: 'tuổi',
    detail_child_discount: 'Trẻ em',
    detail_discount: 'Giảm',
    detail_no_children: 'Không áp dụng cho trẻ em.',
    detail_available: 'Còn',
    detail_slots: 'chỗ trống',
    detail_slots_total: 'chỗ trống (toàn tour)',
    detail_guests_day: 'khách/ngày',
    detail_total_max: 'Tổng',
    detail_max_guests_tour: 'khách tối đa trong 1 tour',

    // Community Feed
    comm_post_placeholder: 'Đăng nhập để chia sẻ trải nghiệm của bạn...',
    comm_post_placeholder_user: 'Chia sẻ khoảnh khắc và trải nghiệm của bạn cùng những người đam mê du lịch.',
    comm_type_image: 'Ảnh',
    comm_type_video: 'Video',
    comm_tag_tour: 'Gắn thẻ tour',
    comm_post_btn: 'Đăng bài',
    comm_no_posts: 'Chưa có bài viết nào trong cộng đồng.',
    comm_comment: 'Bình luận',
    comm_comments: 'Bình luận',
    comm_helpful: 'Hữu ích',
    comm_comment_placeholder: 'Viết bình luận...',
    comm_talking_about: 'Đang nói về:',
    comm_like: 'Thích',
    comm_write_reply: 'Viết phản hồi của bạn...',
    comm_reply: 'Trả lời',
    comm_people: 'người',
    comm_love: 'Yêu thích',
    comm_wow: 'Wow',
    comm_haha: 'Haha',
    comm_sad: 'Buồn',
    comm_angry: 'Phẫn nộ',
    comm_reactions_title: 'Người đã bày tỏ cảm xúc',
    comm_show_more_replies: 'Hiển thị thêm',
    comm_replies_word: 'phản hồi',
    comm_hide_replies: 'Ẩn bớt phản hồi',
    comm_replying_to: 'Đang trả lời',
    comm_admin_badge: 'Quản trị viên',
    comm_title: 'Cộng đồng Travel',
    comm_desc: 'Chia sẻ khoảnh khắc và trải nghiệm của bạn cùng những người đam mê du lịch.',
    comm_all_posts: 'Tất cả bài viết',
    comm_loading_feed: 'Đang tải bảng tin...',
    comm_show_more: 'Xem thêm',
    comm_file_type_error: 'Vui lòng chọn file hình ảnh hoặc video.',
    comm_upload_error: 'Lỗi tải lên file',
    comm_delete_confirm: 'Xóa bài viết này?',
    review_fallback: 'Tour đã đánh giá',
    review_no_reviews: 'Chưa có bình luận nào. Hãy là người đầu tiên đánh giá tour.',

    noti_title: 'Hòm thư / Thông báo',
    noti_unread: 'thông báo chưa đọc',
    noti_new_comment: 'Bình luận mới',
    noti_new_reaction: 'Cảm xúc mới',
    noti_tour_approved_title: 'Tour đã được duyệt',
    noti_tour_rejected_title: 'Tour đã bị từ chối',
    noti_tour_approved_message: 'Tour {title} đã được admin phê duyệt và hiện có thể nhận khách.',
    noti_tour_rejected_message: 'Tour {title} đã bị từ chối. Lý do: {reason}',
    noti_tour_rejected_no_reason: 'Không có lý do cụ thể',
    noti_commented: 'đã bình luận về bài viết của bạn.',
    noti_reacted_comment: 'đã thả cảm xúc bình luận của bạn.',
    noti_reacted_post: 'đã thả cảm xúc bài viết của bạn.',
    noti_empty_title: 'Chưa có thông báo nào',
    noti_empty_desc: 'Khi có người tương tác với bài viết của bạn hoặc có cập nhật mới, thông báo sẽ hiển thị ở đây.',
    noti_delete_title: 'Xóa thông báo',


    footer_address: 'Ngũ Hành Sơn, Đà Nẵng, Việt Nam',
    review_img_optional: 'Đường dẫn hình ảnh minh họa (không bắt buộc)',

    booking_contact_name: 'Tên liên hệ',
    booking_contact_name_ph: 'Nguyễn Văn A',
    booking_phone: 'Số điện thoại',
    booking_select_schedule: 'Chọn lịch trình',
    booking_select_schedule_ph: '-- Chọn lịch --',
    booking_departure_date: 'Ngày đi',
    booking_adults: 'Người lớn',
    booking_children: 'Trẻ em',
    booking_children_under: 'dưới',
    booking_note: 'Ghi chú (tuỳ chọn)',
    booking_note_ph: 'Yêu cầu đặc biệt, dị ứng thực phẩm...',
    booking_promo: 'Mã khuyến mãi',
    booking_apply: 'Áp dụng',
    booking_apply_success: 'Áp dụng mã thành công!',
    booking_invalid_promo: 'Mã không hợp lệ',
    booking_adult_unit: 'người lớn',
    booking_child_unit: 'trẻ em',
    booking_discount: 'Giảm giá',
    booking_total_due: 'Tổng cộng',
    booking_cancel: 'Hủy',
    booking_confirm: 'Xác nhận đặt tour',
    booking_closed: 'Tour đã đóng',
    booking_slot_left: 'chỗ còn',
    booking_max_daily: 'Tối đa',
    booking_max_total: 'Tối đa',
    booking_guests_day: 'khách/ngày',
    booking_guests_total: 'khách toàn tour',
    booking_per_guest: 'khách',
    booking_validate_schedule: 'Vui lòng chọn lịch trình',
    booking_validate_schedule_slots: 'Lịch trình này chỉ còn {count} chỗ',
    booking_validate_window: 'Tour này đã hết thời gian nhận đặt',
    booking_validate_date_min: 'Ngày đi phải nằm trong thời gian tour đang nhận đặt',
    booking_validate_date_max: 'Ngày đi đã vượt quá ngày đóng nhận đặt của tour',
    booking_validate_day_full: 'Tour này đã hết chỗ trong ngày được chọn.',
    booking_validate_daily_remaining: 'Tour này chỉ còn {count} chỗ trong ngày này.',
    booking_validate_total_remaining: 'Tour này chỉ còn {count} chỗ tổng cộng.',
    booking_validate_max_guests: 'Tour này chỉ nhận tối đa {count} khách cho một ngày',
    booking_validate_contact: 'Tên người liên hệ cần tối thiểu 2 ký tự',
    booking_validate_phone: 'Số điện thoại không hợp lệ',
    booking_validate_note: 'Ghi chú tối đa 300 ký tự',
    booking_submit_error: 'Đặt tour thất bại, vui lòng thử lại',

    schedule_title: 'Lịch khởi hành',
    schedule_start: 'Bắt đầu',
    schedule_end: 'Kết thúc',
    schedule_slots: 'Số chỗ',
    schedule_add: 'Thêm',
    schedule_loading: 'Đang tải lịch...',
    schedule_empty: 'Chưa có lịch khởi hành nào.',
    schedule_remaining: 'Còn',
    schedule_slots_empty: 'chỗ trống',
    schedule_load_error: 'Lỗi tải lịch khởi hành',
    schedule_validate_dates: 'Vui lòng chọn ngày bắt đầu và kết thúc',
    schedule_validate_range: 'Ngày kết thúc phải sau hoặc bằng ngày bắt đầu',
    schedule_delete_confirm: 'Bạn có chắc chắn muốn xóa lịch này?',

    host_child_max_age_ph: 'Độ tuổi tối đa tính là trẻ em',
    host_child_discount_ph: '% giảm so với người lớn',
    host_review_modal_title: 'Đánh giá khách hàng',
    host_review_modal_desc: 'Đánh giá khách hàng {name} cho đơn hàng #{id}',
    host_review_rating_label: 'Chất lượng (sao)',
    host_review_comment_label: 'Nhận xét của bạn',
    host_review_comment_ph: 'Khách hàng đã trải nghiệm như thế nào...',
    host_review_submit: 'Gửi đánh giá',
    host_status_approved: 'Đã duyệt',
    host_status_rejected: 'Đã từ chối',
    host_status_suspended: 'Đã tạm khóa',

    back_home: 'Quay lại trang chủ',
    preparing: 'Đang chuẩn bị hành trình...',
    explore_with: 'Khám phá thế giới cùng',
  },
  en: {
    // Header nav
    nav_about: 'About Us',
    nav_experiences: 'Experiences',
    nav_how: 'How It Works',
    nav_community: 'Community',
    nav_faq: 'FAQ',
    nav_dashboard: 'Dashboard',
    nav_preview: 'Tours on Sale',
    nav_login: 'Log In',
    nav_logout: 'Log Out',
    nav_dark_on: 'Switch to dark mode',
    nav_dark_off: 'Switch to light mode',
    lang_toggle: 'Switch to Vietnamese',

    // Hero section
    hero_eyebrow: 'Local Tours in Vietnam',
    hero_title: 'Book tours with clear prices, schedules & real reviews.',
    hero_desc: 'Discover Ha Long Bay, Hoi An, Bat Trang, Sa Pa and many local experiences with a simple booking process and transparent comments.',
    hero_cta_tours: 'View Tours',
    hero_cta_host: 'Become a Host',
    hero_stat_safe: 'Safe & Secure',
    hero_stat_quality: 'Quality',
    hero_stat_review: 'Honest Reviews',

    // About section
    about_eyebrow: 'About Us',
    about_title: 'A streamlined, easy-to-manage booking process',
    about_desc: 'Guests can browse tours and comments before logging in. Logged-in users can book tours, cancel pending orders, and submit reviews.',
    about_f1_title: 'Clear Tour Information',
    about_f1_text: 'Each tour includes location, duration, price in VND, photos and categories for quick filtering.',
    about_f2_title: 'Community Hosts',
    about_f2_text: 'Connect travelers with verified local hosts and guides for a more authentic experience.',
    about_f3_title: 'Accurate Booking Details',
    about_f3_text: 'Email, phone number, departure date and guest count are automatically validated to minimize errors.',

    // Experiences section
    exp_eyebrow: 'Experiences',
    exp_title: 'Tours Available Now',
    exp_desc: 'Tour prices are listed in VND and updated in real-time. Tours with no reviews will show 0.0 stars.',
    exp_search_placeholder: 'Search by tour name, location or category',
    exp_price_from: 'Price from...',
    exp_price_to: 'Price to...',
    exp_all_categories: 'All Categories',
    exp_show_more: 'Show More',
    exp_book: 'Book Tour',
    exp_view_detail: 'View Details',
    exp_no_result: 'No matching tours found.',
    exp_wishlist_login: 'Please log in to add to wishlist',
    exp_guests: 'guests',
    exp_full: 'Full',
    exp_not_open: 'Not Open',

    // How it works
    how_eyebrow: 'How It Works',
    how_title: 'Three Steps to Start Your Journey',
    how_desc: 'The process is kept short so new users can operate quickly.',
    how_s1_title: 'Discover Tours',
    how_s1_text: 'Browse local tours, read real reviews and choose the experience that fits you.',
    how_s2_title: 'Easy Booking',
    how_s2_text: 'Select a date, fill in your contact details and confirm your booking in just a few simple steps.',
    how_s3_title: 'Real Experience',
    how_s3_text: 'Join the tour and share your honest review to help the travel community keep improving.',

    // Community
    community_eyebrow: 'Community',
    community_title: 'Share Your Journey',
    community_view_all: 'View All Posts',

    // Host register
    host_eyebrow: 'For Hosts',
    host_title: 'Become a host and share your local experiences',
    host_desc: 'Fill in the registration form and we will contact you for verification within 24 hours.',
    host_name: 'Full Name',
    host_email: 'Email',
    host_phone: 'Phone Number',
    host_address: 'Home Address',
    host_id: 'National ID / Passport',
    host_exp_location: 'Operating Location',
    host_exp_desc: 'Describe the experience you want to share',
    host_submit: 'Submit Application',
    host_submitting: 'Submitting...',
    host_form_required_error: 'Please complete all host application fields',
    host_contact_invalid_error: 'Email or phone number is invalid',
    host_id_invalid_error: 'ID/Passport must contain exactly 12 digits',
    host_desc_min_error: 'Description must be at least 20 characters',
    host_submit_error: 'Unable to submit host application',
    host_submit_success: 'Host application submitted successfully! Admin will review your request.',
    host_session_expired: 'Your session has expired. Please log in again.',
    host_data_error: 'Unable to read data',
    host_load_error: 'Unable to load dashboard data',
    host_image_type_error: 'Please choose an image file.',
    host_upload_error: 'Image upload failed',
    host_tour_required_error: 'Please complete all tour information',
    host_price_min_error: 'Tour price must be at least 1,000 VND',
    host_max_guests_error: 'Max guests must be from 1 to 1000',
    host_close_date_error: 'Close date must be after or equal to open date',
    host_profile_success: 'Profile updated successfully!',
    host_delete_title: 'Delete Tour',
    host_delete_message: 'Are you sure you want to delete this tour? All related data will be lost.',
    host_review_request_title: 'Request Tour Review',
    host_review_request_message: 'This tour will be sent to Admin for review. You will receive a notification after Admin responds.',
    host_refund_confirm: 'Confirm that you have refunded the customer?',
    host_refund_success: 'Refund status updated successfully.',
    host_refund_error: 'Refund processing failed',
    host_review_success: 'Guest review submitted successfully',
    host_preview_no_booking: 'Hosts do not need to book tours in preview mode!',
    admin_preview_no_booking: 'Admins do not need to book tours in preview mode!',

    // Review
    review_eyebrow: 'Reviews',
    review_title: 'Customer Reviews',
    review_desc: 'Logged-in users can submit a rating and comment. The average tour rating is updated automatically based on customer feedback.',
    review_submit_title: 'Submit Your Review',
    review_select_tour: 'Select Tour',
    review_comment_placeholder: 'Share your experience...',
    review_submit: 'Submit Review',
    review_submitting: 'Submitting...',
    review_login_required: 'Please log in to submit a review.',
    review_choose_tour_error: 'Please select a tour to review',
    review_comment_min_error: 'Comment must be at least 5 characters',
    review_submit_error: 'Unable to submit comment',
    review_submit_success: 'Comment submitted successfully',

    // Footer
    footer_desc: 'A local tour booking platform in Vietnam with a simple and transparent process.',
    footer_links: 'Quick Links',
    footer_contact: 'Contact',
    footer_rights: 'All rights reserved.',

    // FAQ
    faq_eyebrow: 'FAQ',
    faq_title: 'Frequently Asked Questions',
    faq_q1: 'Can I book a tour without logging in?',
    faq_a1: 'Guests can view all tours and reviews without logging in, but must log in or register before booking and submitting reviews.',
    faq_q2: 'How is the star rating calculated?',
    faq_a2: 'New tours default to 0 stars. When a user submits a review, the system automatically calculates the average score and increments the review count.',
    faq_q3: 'Can I cancel my booking?',
    faq_a3: 'Users can cancel pending bookings. Once confirmed, you should contact support to reschedule.',

    // Bookings (user profile)
    booking_my: 'My Bookings',
    booking_tour: 'Tour',
    booking_date: 'Departure Date',
    booking_guests: 'Guests',
    booking_total: 'Total',
    booking_status: 'Status',

    // Host Tabs
    host_tab_overview: 'Overview',
    host_tab_experiences: 'Experiences',
    host_tab_bookings: 'Bookings',
    host_tab_reviews: 'Reviews',
    host_tab_profile: 'Profile',

    // Host Dashboard
    host_dashboard_eyebrow: 'Dashboard',
    host_dashboard_title: 'VietTour Dashboard',
    host_dashboard_desc: 'Manage your tours, bookings, and profile.',
    host_stat_tours: 'Active Tours',
    host_stat_reviews: 'Reviews',
    host_stat_pending: 'Pending Bookings',
    host_stat_revenue: 'Expected Revenue',
    host_chart_title: 'Revenue Chart',
    host_chart_desc: 'Revenue stats for the last 7 days',
    host_chart_total: '7-Day Total',
    host_new_bookings: 'New Bookings',
    host_new_reviews: 'New Reviews',
    host_no_bookings: 'No bookings yet.',
    host_no_reviews: 'No reviews yet.',
    host_refresh: 'Refresh',
    host_chart_earning: 'Net Earnings',
    host_loading: 'Loading data...',
    host_preview_title: 'Tours on Sale',
    host_preview_desc: 'Preview the tour list as displayed to customers.',
    host_search_ph: 'Search by tour name, location or category',
    host_no_desc: 'No description available for this tour.',
    host_max_guests_day: 'guests/day',
    host_booking_period: 'Booking',
    host_price_from: 'From',
    host_view_detail: 'Details',
    host_no_match: 'No matching tours found.',
    host_load_more: 'Load More',
    host_manage_tours: 'Manage Tours',
    host_editing_tour: 'Editing Tour',
    host_add_tour: 'Add Tour',
    host_form_name: 'Tour Name',
    host_form_name_ph: 'Enter tour name',
    host_form_location: 'Location',
    host_form_location_ph: 'Enter location',
    host_form_duration: 'Duration',
    host_form_duration_ph: 'E.g. 2 days 1 night',
    host_form_price: 'Price (VND)',
    host_form_price_ph: 'Enter price',
    host_form_category: 'Category',
    host_form_category_ph: 'Select category',
    host_form_max_guests: 'Max Guests (entire tour)',
    host_form_daily_max: 'Max Guests per Day',
    host_form_open_date: 'Booking Opens',
    host_form_close_date: 'Booking Closes',
    host_form_rooms: 'Rooms',
    host_form_beds: 'Beds',
    host_form_children: 'Allow Children',
    host_form_min_age: 'Minimum Age',
    host_form_child_max_age: 'Child Max Age',
    host_form_child_discount: 'Child Discount (%)',
    host_form_amenities: 'Amenities',
    host_form_amenities_ph: 'Enter amenities (comma separated)',
    host_form_image: 'Cover Image',
    host_form_image_ph: 'URL or upload',
    host_form_upload: 'Upload',
    host_form_gallery: 'Gallery Images',
    host_form_gallery_ph: 'Links separated by commas or spaces',
    host_form_desc: 'Detailed Description',
    host_form_desc_ph: 'Describe the tour to attract customers',
    host_form_save_review: 'Save & Submit for Review',
    host_form_save: 'Save',
    host_form_cancel: 'Cancel',
    host_table_tour: 'Tour',
    host_table_category: 'Category',
    host_table_price: 'Price',
    host_table_capacity: 'Capacity',
    host_table_period: 'Open Period',
    host_table_rating: 'Rating',
    host_table_actions: 'Actions',
    host_guests_total: 'guests (total)',
    host_per_day: '/day',
    host_status_closed: 'Closed (full)',
    host_status_pending_review: 'Pending Admin Review',
    host_status_pending_update: 'Pending Update Review',
    host_status_hidden: 'Hidden',
    host_status_draft: 'Draft',
    host_status_open: 'Open',
    host_status_not_open: 'Not Open Yet',
    host_status_closed_simple: 'Closed',
    host_reopen: 'Reopen',
    host_submit_review: 'Submit',
    host_waiting: 'Waiting...',
    host_no_tours: 'No tours in the system.',
    host_manage_bookings: 'Manage Bookings',
    host_table_order: 'Order',
    host_table_contact: 'Contact',
    host_table_schedule: 'Date/Schedule',
    host_table_finance: 'Finance',
    host_table_status: 'Status',
    host_guests: 'guests',
    host_schedule_id: 'Schedule ID',
    host_earning: 'Net Earnings',
    host_opt_pending: 'Pending',
    host_opt_confirmed: 'Confirmed',
    host_opt_cancelled: 'Cancelled',
    host_opt_unpaid: 'Unpaid',
    host_opt_paid: 'Paid',
    host_refund_req: 'Refund Request',
    host_refunded: 'Refunded',
    host_eval_customer: 'Evaluate Guest',
    host_reviews_title: 'Guest Reviews',
    host_tour_deleted: 'Deleted Tour',
    host_profile_title: 'Personal Profile',
    host_profile_name: 'Display Name',
    host_profile_phone: 'Phone Number',
    host_profile_id: 'ID/Passport',
    host_profile_address: 'Address',
    host_profile_area: 'Operating Area',
    host_profile_desc: 'About Me',
    host_profile_update: 'Update Profile',
    host_changed: 'Changed',
    host_from: 'from',
    host_to: 'to',
    host_no_changes: 'No significant data changes.',
    host_err_old_version: 'Cannot read old version data.',
    host_update_detail: 'Update Details (Compare with old version)',
    host_empty: 'Empty',
    host_yes: 'Yes',
    host_no: 'No',

    // Categories
    cat_nature: 'Nature',
    cat_culture: 'Culture',
    cat_history: 'History',
    cat_culinary: 'Culinary',
    cat_adventure: 'Adventure',
    cat_resort: 'Resort',
    cat_discovery: 'Discovery',
    cat_experience: 'Experience',

    // Auth
    auth_login_title: 'Log In',
    auth_login_desc: 'Log in to book tours, comment and experience our services.',
    auth_email: 'EMAIL',
    auth_email_ph: 'name@example.com',
    auth_password: 'PASSWORD',
    auth_password_forgot: 'Forgot password?',
    auth_password_ph: 'At least 6 characters',
    auth_login_btn: 'Log In',
    auth_no_account: "Don't have an account?",
    auth_register_free: 'Register for free',
    auth_register_title: 'Create Account',
    auth_register_desc: 'Create an account to book tours and comment.',
    auth_fullname: 'FULL NAME',
    auth_fullname_ph: 'John Doe',
    auth_register_btn: 'Register',
    auth_has_account: 'Already have an account?',
    auth_login_now: 'Log in now',
    auth_forgot_title: 'Forgot Password',
    auth_forgot_desc: 'Enter your email and new password to reset it.',
    auth_password_new: 'New Password',
    auth_password_confirm: 'Confirm New Password',
    auth_password_new_ph: 'New password (at least 6 characters)',
    auth_password_confirm_ph: 'Re-enter new password',
    auth_reset_btn: 'Reset Password',
    auth_or_continue_with: 'Or continue with',
    auth_google_error: 'Google sign-in failed',
    auth_google_cancel: 'You cancelled Google sign-in',
    auth_google_email_exists: 'This email is already registered. Signing in...',

    // User Profile
    profile_title: 'Personal Information',
    profile_bookings: 'Bookings',
    profile_cancelled: 'Cancelled',
    profile_favorites: 'Favorites',
    profile_email_fixed: 'EMAIL',
    profile_fullname: 'FULL NAME',
    profile_phone: 'PHONE NUMBER',
    profile_avatar: 'UPLOAD AVATAR',
    profile_avatar_select: 'Choose file',
    profile_avatar_none: 'No file chosen',
    profile_address: 'ADDRESS',
    profile_save: 'Save Changes',
    profile_booking_date: 'Booking date:',
    profile_guests: 'guests',
    profile_payment: 'Payment:',
    profile_no_cancelled: 'You have no cancelled tours.',
    profile_no_wishlists: 'You have no favorite tours.',

    // More detail
    detail_review_count: 'comment',
    detail_reviews_count: 'comments',
    detail_tour_count: 'tour',
    detail_tours_count: 'tours',
    detail_hour: 'hours',
    detail_rating_count: 'reviews',

    booking_status_pending: 'Pending',
    booking_status_confirmed: 'Confirmed',
    booking_status_cancelled: 'Cancelled',
    booking_payment_unpaid: 'Unpaid',
    booking_payment_paid: 'Paid',
    booking_payment_refunded: 'Refunded',

    // Misc
    // Detail Modal
    detail_host_info: 'Host Information',
    detail_capacity: 'Capacity',
    detail_booking_open: 'Booking Period',
    detail_child_policy: 'Child Policy',
    detail_status: 'Status',
    detail_room: 'Room',
    detail_bed: 'Bed',
    detail_rooms: 'Rooms',
    detail_beds: 'Beds',
    detail_amenities: 'Amenities',
    detail_schedules: 'Upcoming Schedules',
    detail_gallery: 'Gallery',
    detail_description: 'Experience Description',
    detail_map: 'Location Map',
    detail_close: 'Close',
    detail_book_now: 'Book Now',
    detail_tour_closed: 'Tour Closed',
    detail_age_from: 'Age: from',
    detail_age_to: 'years old',
    detail_child_discount: 'Children',
    detail_discount: 'Discount',
    detail_no_children: 'Not applicable for children.',
    detail_available: 'Available',
    detail_slots: 'slots',
    detail_slots_total: 'slots (entire tour)',
    detail_guests_day: 'guests/day',
    detail_total_max: 'Total max',
    detail_max_guests_tour: 'guests per tour',

    // Community Feed
    comm_post_placeholder: 'Log in to share your experience...',
    comm_post_placeholder_user: 'Share your moments and experiences with travel enthusiasts.',
    comm_type_image: 'Image',
    comm_type_video: 'Video',
    comm_tag_tour: 'Tag a tour',
    comm_post_btn: 'Post',
    comm_no_posts: 'No posts in the community yet.',
    comm_comment: 'Comment',
    comm_comments: 'Comments',
    comm_helpful: 'Helpful',
    comm_comment_placeholder: 'Write a comment...',
    comm_talking_about: 'Talking about:',
    comm_like: 'Like',
    comm_write_reply: 'Write your reply...',
    comm_reply: 'Reply',
    comm_people: 'people',
    comm_love: 'Love',
    comm_wow: 'Wow',
    comm_haha: 'Haha',
    comm_sad: 'Sad',
    comm_angry: 'Angry',
    comm_reactions_title: 'People who reacted',
    comm_show_more_replies: 'Show',
    comm_replies_word: 'more replies',
    comm_hide_replies: 'Hide replies',
    comm_replying_to: 'Replying to',
    comm_admin_badge: 'Admin',
    comm_title: 'Travel Community',
    comm_desc: 'Share your moments and travel experiences with people who love exploring.',
    comm_all_posts: 'All Posts',
    comm_loading_feed: 'Loading feed...',
    comm_show_more: 'Show More',
    comm_file_type_error: 'Please choose an image or video file.',
    comm_upload_error: 'File upload failed',
    comm_delete_confirm: 'Delete this post?',
    review_fallback: 'Reviewed tour',
    review_no_reviews: 'No reviews yet. Be the first to review this tour.',

    noti_title: 'Inbox / Notifications',
    noti_unread: 'unread notifications',
    noti_new_comment: 'New comment',
    noti_new_reaction: 'New reaction',
    noti_tour_approved_title: 'Tour Approved',
    noti_tour_rejected_title: 'Tour Rejected',
    noti_tour_approved_message: 'Tour {title} has been approved by the admin and is now available for guests.',
    noti_tour_rejected_message: 'Tour {title} has been rejected. Reason: {reason}',
    noti_tour_rejected_no_reason: 'No reason provided',
    noti_commented: 'commented on your post.',
    noti_reacted_comment: 'reacted to your comment.',
    noti_reacted_post: 'reacted to your post.',
    noti_empty_title: 'No notifications yet',
    noti_empty_desc: 'When someone interacts with your post or there is a new update, notifications will appear here.',
    noti_delete_title: 'Delete notification',

    footer_address: 'Ngu Hanh Son, Da Nang, Vietnam',
    review_img_optional: 'Image URL (optional)',

    booking_contact_name: 'Contact Name',
    booking_contact_name_ph: 'John Doe',
    booking_phone: 'Phone Number',
    booking_select_schedule: 'Select Schedule',
    booking_select_schedule_ph: '-- Select schedule --',
    booking_departure_date: 'Departure Date',
    booking_adults: 'Adults',
    booking_children: 'Children',
    booking_children_under: 'under',
    booking_note: 'Note (optional)',
    booking_note_ph: 'Special requests, food allergies...',
    booking_promo: 'Promo Code',
    booking_apply: 'Apply',
    booking_apply_success: 'Promo code applied!',
    booking_invalid_promo: 'Invalid code',
    booking_adult_unit: 'adults',
    booking_child_unit: 'children',
    booking_discount: 'Discount',
    booking_total_due: 'Total',
    booking_cancel: 'Cancel',
    booking_confirm: 'Confirm Booking',
    booking_closed: 'Tour Closed',
    booking_slot_left: 'slots left',
    booking_max_daily: 'Max',
    booking_max_total: 'Max',
    booking_guests_day: 'guests/day',
    booking_guests_total: 'guests total',
    booking_per_guest: 'guest',
    booking_validate_schedule: 'Please select a schedule',
    booking_validate_schedule_slots: 'This schedule only has {count} slots left',
    booking_validate_window: 'This tour is no longer accepting bookings',
    booking_validate_date_min: 'Departure date must be within the booking period',
    booking_validate_date_max: 'Departure date is past the booking close date',
    booking_validate_day_full: 'This tour is fully booked on the selected date.',
    booking_validate_daily_remaining: 'This tour only has {count} slots left on this date.',
    booking_validate_total_remaining: 'This tour only has {count} total slots left.',
    booking_validate_max_guests: 'This tour accepts a maximum of {count} guests per day',
    booking_validate_contact: 'Contact name must be at least 2 characters',
    booking_validate_phone: 'Invalid phone number',
    booking_validate_note: 'Note must be 300 characters or fewer',
    booking_submit_error: 'Booking failed, please try again',

    schedule_title: 'Departure Schedules',
    schedule_start: 'Start',
    schedule_end: 'End',
    schedule_slots: 'Slots',
    schedule_add: 'Add',
    schedule_loading: 'Loading schedules...',
    schedule_empty: 'No departure schedules yet.',
    schedule_remaining: 'Remaining',
    schedule_slots_empty: 'open slots',
    schedule_load_error: 'Failed to load departure schedules',
    schedule_validate_dates: 'Please choose start and end dates',
    schedule_validate_range: 'End date must be after or equal to start date',
    schedule_delete_confirm: 'Are you sure you want to delete this schedule?',

    host_child_max_age_ph: 'Maximum age counted as a child',
    host_child_discount_ph: '% discount from adult price',
    host_review_modal_title: 'Evaluate Guest',
    host_review_modal_desc: 'Evaluate guest {name} for order #{id}',
    host_review_rating_label: 'Quality (stars)',
    host_review_comment_label: 'Your Comment',
    host_review_comment_ph: 'How was this guest experience...',
    host_review_submit: 'Submit Review',
    host_status_approved: 'Approved',
    host_status_rejected: 'Rejected',
    host_status_suspended: 'Suspended',

    loading: 'Loading...',
    error_generic: 'An error occurred. Please try again.',
    logout_success: 'Logged out successfully',
    tour_not_bookable: 'This tour is not open or is no longer accepting bookings.',
    back_home: 'Back to Home',
    preparing: 'Preparing your journey...',
    explore_with: 'Explore the world with',
  }
} as const;

export type TranslationKey = keyof typeof translations['vi'] | keyof typeof translations['en'];

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  tCategory: (cat: string) => string;
  tDynamic: (text: string | null | undefined) => string;
}

const dynamicTranslations: Record<string, string> = {
  '2 giờ': '2 hours',
  '1 ngày': '1 day',
  'du lịch đà nẵng': 'Da Nang travel',
  'trải nghiệm tuyệt vời': 'great experience',
  'Vịnh Hạ Long': 'Ha Long Bay',
  'Tour Vịnh Hạ Long 2 ngày 1 đêm': 'Halong Bay Tour 2 days 1 night',
  'Khám phá Phố cổ Hội An': 'Explore Hoi An Ancient Town',
  'Tour Sapa - Phan Xi Păng 3 ngày 2 đêm': 'Sapa - Fansipan Tour 3 days 2 nights',
  'Nghỉ dưỡng tại Phú Quốc': 'Phu Quoc Resort Vacation',
  'Khám phá Địa đạo Củ Chi': 'Explore Cu Chi Tunnels',
  'Lớp học nấu ăn cùng người bản địa': 'Local Cooking Class',
  'Khám phá Làng Gốm Bát Tràng': 'Explore Bat Trang Pottery Village',
  'Tour Trekking Dạo Bản Sa Pa': 'Sa Pa Village Trekking Tour',
  'Hà Nội': 'Hanoi',
  'Quảng Ninh': 'Quang Ninh',
  'Lào Cai': 'Lao Cai',
  'Kiên Giang': 'Kien Giang',
  'Quảng Nam': 'Quang Nam',
  'Hồ Chí Minh': 'Ho Chi Minh City',
  'Đà Nẵng': 'Da Nang',
  'Khám phá Vịnh Hạ Long bằng du thuyền trong ngày, đi qua các cụm đảo đá vôi, làng chài và những điểm ngắm cảnh nổi bật. Tour phù hợp cho du khách muốn có một lịch trình gọn, dễ đặt và nhiều thời gian chụp ảnh.': 'Explore Halong Bay by day cruise, passing through limestone island clusters, fishing villages, and prominent scenic spots. Suitable for tourists wanting a compact, easy-to-book itinerary with plenty of time for photography.',
  'Cùng host địa phương đi chợ, chọn nguyên liệu và học nấu các món Việt quen thuộc. Trải nghiệm tập trung vào kỹ thuật nấu ăn, câu chuyện ẩm thực vùng miền và bữa ăn chung cuối buổi.': 'Go to the market with a local host, choose ingredients, and learn to cook familiar Vietnamese dishes. The experience focuses on cooking techniques, regional culinary stories, and a shared meal at the end.',
  'Tìm hiểu quy trình làm gốm thủ công, thử tạo hình sản phẩm và nghe nghệ nhân chia sẻ về làng nghề. Hoạt động phù hợp cho gia đình, nhóm bạn hoặc du khách thích trải nghiệm sáng tạo.': 'Learn about the manual pottery making process, try shaping products, and listen to artisans share about the craft village. Suitable for families, groups of friends, or tourists who enjoy creative experiences.',
  'Đi bộ qua ruộng bậc thang, bản làng và các cung đường núi ở Sa Pa cùng người dẫn địa phương. Lịch trình cân bằng giữa vận động, ngắm cảnh và tìm hiểu đời sống cộng đồng.': 'Trek through terraced fields, villages, and mountain roads in Sa Pa with a local guide. The itinerary balances exercise, sightseeing, and learning about community life.',
  'Tour trải nghiệm địa phương được thiết kế để du khách hiểu rõ văn hóa, cảnh quan và nhịp sống bản địa. Lịch trình phù hợp cho nhóm nhỏ, có host hướng dẫn và thông tin chi phí minh bạch.': 'Local experience tour designed for tourists to understand the culture, landscapes, and local pace of life. Suitable for small groups, with a host guide and transparent cost information.'
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'vi',
  setLang: () => { },
  t: (key) => translations.vi[key],
  tCategory: (cat) => cat,
  tDynamic: (text) => text || ''
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('lang') as Language) || 'vi';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('lang', newLang);
  };

  const t = (key: TranslationKey): string => translations[lang][key] || key;

  const tCategory = (cat: string): string => {
    const key = Object.keys(translations.vi).find(
      (k) => translations.vi[k as TranslationKey] === cat
    );
    if (key && translations[lang][key as TranslationKey]) {
      return translations[lang][key as TranslationKey];
    }
    return cat;
  };

  const tDynamic = (text: string | null | undefined): string => {
    if (!text) return '';
    if (lang === 'vi') return text;
    return dynamicTranslations[text] || text;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, tCategory, tDynamic }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
